prooph_event_store:
  stores:
    farm_market_store:
      event_store: Prooph\EventStore\Pdo\MySqlEventStore
      repositories:
        farm_collection:
          repository_class: App\FarmMarket\Model\Farm\Repository\EventStoreFarmCollection
          aggregate_type: App\FarmMarket\Model\Farm\Farm
          aggregate_translator: prooph_event_sourcing.aggregate_translator
        App\FarmMarket\Model\Farm\Repository\EventStoreFarmCollection:
          aggregate_type: App\FarmMarket\Model\Farm\Farm
          aggregate_translator: prooph_event_sourcing.aggregate_translator

  projection_managers:
    market_projection_manager:
      event_store: Prooph\EventStore\Pdo\MySqlEventStore
      connection: 'doctrine.pdo.connection'
      projections:
        farm_projection:
          projection: App\FarmMarket\Projection\FarmProjection
          read_model: App\FarmMarket\Projection\FarmReadModel

services:
  Prooph\EventStore\Pdo\MySqlEventStore:
    arguments: ['@prooph_event_store.message_factory', '@doctrine.pdo.connection', '@prooph_event_store.single_stream_strategy']

  doctrine.pdo.connection:
    class: PDO
    factory: ['@database_connection', getWrappedConnection]

  prooph_event_store.single_stream_strategy:
    class: Prooph\EventStore\Pdo\PersistenceStrategy\MySqlSingleStreamStrategy

  prooph_event_sourcing.aggregate_translator:
    class: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator