# app/config/config.yml or (flex) config/packages/prooph_service_bus.yaml
prooph_service_bus:
  command_buses:
    farm_market_command_bus: ~

  event_buses:
    todo_event_bus:
      plugins:
      - 'prooph_service_bus.on_event_invoke_strategy'
      router:
        type: 'prooph_service_bus.event_bus_router'