Farm:
  type: object
  config:
    description: "A Farm"
    fields:
      id:
        type: "Uuid!"
        description: "The unique ID of the farm."
      name:
        type: "String!"
      email:
        type: "String!"
      location:
        type: "GeoPoint"
